# for st in 375 350 325 300; do
#     torchrun --nnodes=1 --nproc_per_node=8 sample_ddp.py --model DiT-L/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/022-DiT-B-2-imagenet-ft-kl=0.0005/checkpoints/0400000.pt --sample-dir /home/ubuntu/fast-DiT/results/022-DiT-B-2-imagenet-ft-kl=0.0005/samples  --vae ours --vae-name ft-kl=0.0005 --vae-ckpt /home/ubuntu/latent-diffusion/logs/resume-kl-f8-openimages-ft-kl-0.00005/checkpoints/epoch=000005.ckpt
# done

# torchrun --nnodes=1 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/024-DiT-B-2-imagenet-equi-prior-preserve/checkpoints/0400000.pt --sample-dir /home/ubuntu/fast-DiT/results/024-DiT-B-2-imagenet-equi-prior-preserve/samples  --vae ours --vae-name f8-kl-equi-prior-preserve --vae-ckpt /home/ubuntu/latent-diffusion/logs/resume-kl-f8-openimages-equi-prior_preserve/checkpoints/save_epoch_5.ckpt
# torchrun --nnodes=1 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/047-DiT-B-2-imagenet-equi-unifrom-sampling-lb-0.5/checkpoints/checkpoints/0400000.pt --sample-dir /home/ubuntu/fast-DiT/results/047-DiT-B-2-imagenet-equi-unifrom-sampling-lb-0.5/samples --vae ours --vae-name f8-kl-equi-unifrom-sampling-lb-0.5 --vae-ckpt /home/ubuntu/latent-diffusion/logs/resume-kl-f8-openimages-equi-unifrom-sampling-lb-0.5/checkpoints/save_epoch_5.ckpt


torchrun --nnodes=1 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/031-DiT-B-2-imagenet-sd-xl/checkpoints/0400000.pt --sample-dir /home/ubuntu/fast-DiT/results/031-DiT-B-2-imagenet-sd-xl/samples --vae xl --vae-name xl  --vae-scaling-factor 0.13025 --ref-batch /data/imagenet/val.npz
torchrun --nnodes=1 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/031-DiT-B-2-imagenet-sd-xl/checkpoints/0400000.pt --sample-dir /home/ubuntu/fast-DiT/results/031-DiT-B-2-imagenet-sd-xl/samples --vae xl --vae-name xl  --ddpm True --cfg-scale 1.0 --vae-scaling-factor 0.13025
torchrun --nnodes=1 --master-port 1332 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/032-DiT-B-2-imagenet-sd-xl-scale-flip-prior-preserve/checkpoints/0400000.pt  --sample-dir /home/ubuntu/fast-DiT/results/032-DiT-B-2-imagenet-sd-xl-scale-flip-prior-preserve/samples --vae hf --vae-name xl-scale-flip-prior-preserve  --ddpm True --cfg-scale 1.0 --vae-scaling-factor 0.1045


torchrun --nnodes=1 --master-port 1332 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/022-DiT-B-2-imagenet-ft-kl=0.0005/checkpoints/0400000.pt  --sample-dir /home/ubuntu/fast-DiT/results/022-DiT-B-2-imagenet-ft-kl=0.0005/samples --vae ours --vae-name ft-kl=0.0005  --ddpm True --cfg-scale 1.0 --vae-ckpt /home/ubuntu/latent-diffusion/logs/resume-kl-f8-openimages-ft-kl-0.00005/checkpoints/epoch=000005.ckpt  
torchrun --nnodes=1 --master-port 1332 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/032-DiT-B-2-imagenet-sd-xl-scale-flip-prior-preserve/checkpoints/0400000.pt  --sample-dir /home/ubuntu/fast-DiT/results/032-DiT-B-2-imagenet-sd-xl-scale-flip-prior-preserve/samples --vae ours --vae-name scale-flip-prior-preserve  --ddpm True --cfg-scale 1.0 --vae-ckpt /home/ubuntu/latent-diffusion/logs/resume-kl-f8-openimages-equi-prior_preserve/checkpoints/save_epoch_5.ckpt 

torchrun --nnodes=1 --master-port 1332 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/042-DiT-B-2-imagenet-ema/checkpoints/0400000.pt  --sample-dir /home/ubuntu/fast-DiT/results/042-DiT-B-2-imagenet-ema/samples --vae ema --vae-name ema  --ddpm True --cfg-scale 1.0 

torchrun --nnodes=1 --master-port 1332 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/043-DiT-B-2-imagenet-f8-kl/checkpoints/0400000.pt  --sample-dir /home/ubuntu/fast-DiT/results/043-DiT-B-2-imagenet-f8-kl/samples --vae ours --vae-name f8-kl  --ddpm True --cfg-scale 1.0 --vae-ckpt /home/ubuntu/latent-diffusion/kl-f8/model.ckpt

torchrun --nnodes=1 --master-port 1332 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/032-DiT-B-2-imagenet-scale-equi-uniform/checkpoints/0400000.pt  --sample-dir /home/ubuntu/fast-DiT/results/032-DiT-B-2-imagenet-scale-equi-uniform/samples --vae ours --vae-name scale-equi-uniform  --ddpm True --cfg-scale 1.0 --vae-ckpt /home/ubuntu/latent-diffusion/logs/rresume-kl-f8-openimages-scale-equi-uniform/checkpoints/save_epoch_5.ckpt

torchrun --nnodes=1 --master-port 1332 --nproc_per_node=8 sample_ddp.py --model DiT-B/2 --num-fid-samples 50000 --ckpt /home/ubuntu/fast-DiT/results/047-DiT-B-2-imagenet-equi-unifrom-sampling-lb-0.5/checkpoints/checkpoints/0400000.pt  --sample-dir /home/ubuntu/fast-DiT/results/047-DiT-B-2-imagenet-equi-unifrom-sampling-lb-0.5/samples --vae ours --vae-name equi-unifrom-sampling-lb-0.5  --ddpm True --cfg-scale 1.0 --vae-ckpt /home/ubuntu/latent-diffusion/logs/rresume-kl-f8-openimages-scale-equi-uniform/checkpoints/save_epoch_5.ckpt
